apache/incubator-hugegraph-ai

- hugegraph-python/example/client_test.py
In the code located at example/client_test.py, there is an import error. The code incorrectly attempts to import the HugeGraph class from the example.test_hugegraph module. However, the correct module should be example.hugegraph_test.
I have fixed this issue by modifying the import statement in example/client_test.py from:
```from example.test_hugegraph import HugeGraph```
to
```from example.hugegraph_test import HugeGraph```
> fix: import error

- .github/workflows/check-dependencies.yml
refer to https://github.com/apache/incubator-hugegraph/pull/2308
> fix: base-ref/head-ref missed in dependency-check-ci on branch push

- .github/workflows/hugegraph-python-client.yml
- hugegraph-python-client/src/tests/api/test_traverser.py
faild jobs: https://github.com/apache/incubator-hugegraph-ai/actions/runs/8673001982/job/23783894307
doc: https://hugegraph.apache.org/cn/docs/clients/restful-api/traverser/#3221-fusiform-similarity
pass in 1.2 and fail in 1.3?
Related PR: https://github.com/apache/incubator-hugegraph/pull/2458
> fix: fusiform_similarity test in traverser for server 1.3.0

- .github/workflows/black.yml
According to https://github.com/apache/incubator-hugegraph-ai/issues/46, I think black for code format can be supported by black integration with github actions([black.readthedocs.io/en/stable/integrations/github_actions.html](https://black.readthedocs.io/en/stable/integrations/github_actions.html)).
the workflow fails if Black finds files that need to be formatted, as can be seen in https://github.com/ChenZiHong-Gavin/incubator-hugegraph-ai/pull/17
so i think everyone should run black in ./style/code_format_and_analysis.sh before commit. (Perhaps it would be better to automatically trigger [the process] through GitHub Hooks rather than running it manually.)
after that, Black passes the workflow, as can be seen in https://github.com/ChenZiHong-Gavin/incubator-hugegraph-ai/pull/18
> chore: introduce black for code format in github actions

- hugegraph-llm/README.md
- hugegraph-llm/requirements.txt
- hugegraph-llm/src/hugegraph_llm/config/generate.py
Add an update option to let users choose to fix this.
> fix(llm): avoid generating config twice

- hugegraph-llm/src/hugegraph_llm/api/rag_api.py
- hugegraph-llm/src/hugegraph_llm/demo/rag_web_demo.py
1. add auth to gradio(using auth provided by gradio)
auth – If provided, username and password (or list of username-password tuples) required to access the gradio app. Can also provide function that takes username and password and returns True if valid login.
refer: https://www.gradio.app/main/docs/gradio/blocks
2. add auth to fastapi(using APIRouter)
refer: https://fastapi.tiangolo.com/reference/apirouter/#fastapi.APIRouter
> feat(llm): add auth for fastapi and gradio

- hugegraph-llm/src/hugegraph_llm/api/models/rag_requests.py
- hugegraph-llm/src/hugegraph_llm/api/rag_api.py
- hugegraph-llm/src/hugegraph_llm/config/__init__.py
- hugegraph-llm/src/hugegraph_llm/config/config.py
- hugegraph-llm/src/hugegraph_llm/demo/rag_web_demo.py
- hugegraph-llm/src/hugegraph_llm/models/rerankers/__init__.py
- hugegraph-llm/src/hugegraph_llm/models/rerankers/cohere.py
- hugegraph-llm/src/hugegraph_llm/models/rerankers/init_reranker.py
- hugegraph-llm/src/hugegraph_llm/models/rerankers/siliconflow.py
- hugegraph-llm/src/hugegraph_llm/operators/common_op/merge_dedup_rerank.py
- hugegraph-llm/src/hugegraph_llm/operators/graph_rag_task.py
- hugegraph-llm/src/hugegraph_llm/operators/hugegraph_op/graph_rag_query.py
- hugegraph-llm/src/hugegraph_llm/operators/llm_op/answer_synthesize.py
> feat(llm): support multi reranker & enhance the UI

- hugegraph-llm/src/hugegraph_llm/api/rag_api.py
- hugegraph-llm/src/hugegraph_llm/config/config.py
- hugegraph-llm/src/hugegraph_llm/config/config_data.py
- hugegraph-llm/src/hugegraph_llm/demo/rag_demo/configs_block.py
- hugegraph-llm/src/hugegraph_llm/demo/rag_demo/rag_block.py
- hugegraph-llm/src/hugegraph_llm/demo/rag_demo/vector_graph_block.py
- hugegraph-llm/src/hugegraph_llm/indices/vector_index.py
- hugegraph-llm/src/hugegraph_llm/middleware/middleware.py
- hugegraph-llm/src/hugegraph_llm/operators/document_op/word_extract.py
- hugegraph-llm/src/hugegraph_llm/operators/hugegraph_op/commit_to_hugegraph.py
- hugegraph-llm/src/hugegraph_llm/operators/hugegraph_op/graph_rag_query.py
- hugegraph-llm/src/hugegraph_llm/operators/llm_op/answer_synthesize.py
- hugegraph-llm/src/hugegraph_llm/operators/llm_op/disambiguate_data.py
- hugegraph-llm/src/hugegraph_llm/operators/llm_op/keyword_extract.py
- hugegraph-llm/src/hugegraph_llm/operators/llm_op/property_graph_extract.py
- hugegraph-llm/src/hugegraph_llm/utils/graph_index_utils.py
- hugegraph-python-client/src/pyhugegraph/client.py
- style/pylint.conf
1. disable pylint `R0917 (too many positional arguments)`
2. fix `W1203: Use lazy % formatting in logging functions`, ...
> fix: pylint for ci

- .asf.yaml
> fix: lowercase the repo label

- .gitattributes
> chore(dist): exclude binary files when exporting source package

- hugegraph-ml/src/hugegraph_ml/examples/correct_and_smooth_example.py
- hugegraph-ml/src/hugegraph_ml/examples/gatne_example.py
- hugegraph-ml/src/hugegraph_ml/models/agnn.py
- hugegraph-ml/src/hugegraph_ml/models/appnp.py
- hugegraph-ml/src/hugegraph_ml/models/arma.py
- hugegraph-ml/src/hugegraph_ml/models/bgnn.py
- hugegraph-ml/src/hugegraph_ml/models/bgrl.py
- hugegraph-ml/src/hugegraph_ml/models/care_gnn.py
- hugegraph-ml/src/hugegraph_ml/models/cluster_gcn.py
- hugegraph-ml/src/hugegraph_ml/models/correct_and_smooth.py
- hugegraph-ml/src/hugegraph_ml/models/dagnn.py
- hugegraph-ml/src/hugegraph_ml/models/deepergcn.py
- hugegraph-ml/src/hugegraph_ml/models/gatne.py
- hugegraph-ml/src/hugegraph_ml/models/pgnn.py
- hugegraph-ml/src/hugegraph_ml/models/seal.py
- hugegraph-ml/src/hugegraph_ml/tasks/fraud_detector_caregnn.py
- hugegraph-ml/src/tests/test_examples/test_examples.py
pylint :
https://github.com/apache/incubator-hugegraph-ai/actions/runs/11817271374/job/32922327458?pr=111
> fix(ml): handle pylint warning

- hugegraph-llm/src/hugegraph_llm/api/models/rag_requests.py
- hugegraph-llm/src/hugegraph_llm/api/rag_api.py
Solve the problem that the final result is not as expected when the `answer_prompt` in the body parameter of `/rag` api is `None` or an empty string
> fix(llm): answer prompt None value effect

- hugegraph-llm/src/hugegraph_llm/api/admin_api.py
- hugegraph-llm/src/hugegraph_llm/demo/rag_demo/admin_block.py
- hugegraph-llm/src/hugegraph_llm/demo/rag_demo/app.py
- hugegraph-llm/src/hugegraph_llm/demo/rag_demo/configs_block.py
- hugegraph-llm/src/hugegraph_llm/demo/rag_demo/rag_block.py
- hugegraph-llm/src/hugegraph_llm/models/embeddings/qianfan.py
- hugegraph-llm/src/hugegraph_llm/models/llms/qianfan.py
Since https://github.com/apache/incubator-hugegraph-ai/pull/122, we recommend:
- use `Config` class and its setting instances(e.g. `admin_settings`) to load configs
- not to use `os.getenv` directly because it may not the same with `.env` file. But if we set some values in environ, they will be automatically loaded into settings.
> fix(llm): replace getenv usage to settings

- hugegraph-llm/src/hugegraph_llm/utils/graph_index_utils.py
the `InfoExtract` corresponding to 'tripls' was incorrectly called; instead, the `PropertyGraphExtract` corresponding to 'property_graph' should have been called
So, change `extract_info(example_prompt, "triples")` to `extract_info(example_prompt, "property_graph")`
> fix(llm): extract_graph_data use wrong method

- hugegraph-llm/src/hugegraph_llm/config/models/base_prompt_config.py
- hugegraph-llm/src/hugegraph_llm/config/prompt_config.py
- hugegraph-llm/src/hugegraph_llm/demo/rag_demo/app.py
- hugegraph-llm/src/hugegraph_llm/demo/rag_demo/vector_graph_block.py
- hugegraph-llm/src/hugegraph_llm/operators/hugegraph_op/fetch_graph_data.py
- hugegraph-llm/src/hugegraph_llm/operators/index_op/build_semantic_index.py
- hugegraph-llm/src/hugegraph_llm/resources/demo/config_input_text.yaml
- hugegraph-llm/src/hugegraph_llm/utils/graph_index_utils.py
- hugegraph-llm/src/hugegraph_llm/utils/vector_index_utils.py
1. **Modify the return messages of `Get Vector Index Info`** . Display the number of elements in **"chunk vector"** and **"graph vid vector"** separately.
`{
"embed_dim": 1024,
"vector_info": {
"chunk_vector_num": 8,
"graph_vid_vector_num": 483,
"graph_properties_vector_num": 8
}
}`
2. **Modify the return messages of `Get Graph Index Info`** . Display the number of vertices and edges. Display the first 100 edges.
`{
"num_vertices": [
483
],
"num_edges": [
692
],
"vertices": [
"12:James",
"12:Sarah"
....],
"edges": [
"S9:徐起>12>12>>S10:冀RM78Y7!小型轿车!徐起",
"S9:刘雪峰>11>11>>S11:未与前车保持足以采取紧急制动措施的安全距离",
....],
"vid_index": {
"embed_dim": 1024,
"num_vectors": 483,
"num_vids": 483
}
}
`
3. **When a user simultaneously employs text and files, a `log.error` pops up.**
4. add doc_input_text into …
> feat(llm): Modify the return messages of Get Vector Index Info and Get Graph Index Info

- hugegraph-llm/src/hugegraph_llm/utils/hugegraph_utils.py
**1 file:**
- hugegraph-llm/src/hugegraph_llm/utils/hugegraph_utils.py
**2 points:**
- Modified the format of the backup data (vertices.json, edges.json, and schema.json)
- Automatically select and return either schema.groovy or schema.json
> refactor(llm): return schema.groovy first when backup graph data

- hugegraph-llm/src/hugegraph_llm/demo/rag_demo/app.py
Fixes #107 
Fix: Enable FastAPI auto-reload in development mode.
Modifications:-
Modified uvicorn command such that it calls the function crate_app which returns the gradio app.
disabled log propagation for Uvicorn's access logs (logs of HTTP requests).
How to Test:-
Run python3 -m hugegraph_llm.demo.rag_demo.app in CLI
Modify any .py file in the project.
The server should restart automatically.
> fix(llm): enable fastapi auto reload function

- .gitignore
- hugegraph-llm/README.md
- hugegraph-llm/src/hugegraph_llm/api/models/rag_requests.py
- hugegraph-llm/src/hugegraph_llm/api/rag_api.py
- hugegraph-llm/src/hugegraph_llm/config/hugegraph_config.py
- hugegraph-llm/src/hugegraph_llm/config/prompt_config.py
- hugegraph-llm/src/hugegraph_llm/demo/rag_demo/app.py
- hugegraph-llm/src/hugegraph_llm/demo/rag_demo/configs_block.py
- hugegraph-llm/src/hugegraph_llm/demo/rag_demo/vector_graph_block.py
- hugegraph-llm/src/hugegraph_llm/indices/graph_index.py
- hugegraph-llm/src/hugegraph_llm/operators/hugegraph_op/commit_to_hugegraph.py
- hugegraph-llm/src/hugegraph_llm/operators/hugegraph_op/graph_rag_query.py
- hugegraph-llm/src/hugegraph_llm/operators/hugegraph_op/schema_manager.py
- hugegraph-llm/src/hugegraph_llm/operators/index_op/semantic_id_query.py
- hugegraph-llm/src/hugegraph_llm/utils/hugegraph_utils.py
- hugegraph-ml/src/hugegraph_ml/data/hugegraph2dgl.py
- hugegraph-ml/src/hugegraph_ml/utils/dgl2hugegraph_utils.py
- hugegraph-python-client/src/pyhugegraph/client.py
- hugegraph-python-client/src/pyhugegraph/example/hugegraph_example.py
- hugegraph-python-client/src/pyhugegraph/example/hugegraph_test.py
- hugegraph-python-client/src/pyhugegraph/utils/huge_config.py
- hugegraph-python-client/src/pyhugegraph/utils/huge_requests.py
- hugegraph-python-client/src/tests/client_utils.py
This pull request refactors multiple modules to replace separate IP and port parameters with a unified URL parameter, addressing issue (fix #191). Key changes include updating configuration classes, client constructors, and example/test files to use "url" consistently, as well as modifying related API endpoints and configuration docs.
> refactor: replace the IP + Port with URL

- hugegraph-llm/src/hugegraph_llm/operators/index_op/build_semantic_index.py
After deleting vertices, running `update_vid_embedding` does **not** successfully remove the corresponding vectors.
* 13 vertices
* 13 `vid` embeddings
* 0 vertices
* Output shows: “Removed 13 vectors”
However, calling `get_vector_index_info` still shows 13 `vid` embeddings.
---
```python
def get_vector_index_info():
chunk_vector_index = VectorIndex.from_index_file(
os.path.join(resource_path, huge_settings.graph_name, "chunks")
)
graph_vid_vector_index = VectorIndex.from_index_file(
os.path.join(resource_path, huge_settings.graph_name, "graph_vids")
)
return json.dumps({
"embed_dim": chunk_vector_index.index.d,
"vector_info": {
"chunk_vector_num": chunk_vector_index.index.ntotal,
"graph_vid_vector_num": graph_vid_vector_index.index.ntotal,
"graph_properties_vector_num": …
```
> fix(llm): failed to remove vectors when updating vid embedding

- .github/pull.yml
- .github/workflows/sync.yml
- hugegraph-ml/src/hugegraph_ml/models/seal.py
This PR includes the following changes:
1. chore(workflow):
-	Add .github/pull.yml to configure pull request rules for automatic syncing with the upstream apache/main branch, including assignees and reviewers.
- Add .github/workflows/sync.yml to enable scheduled (every 3 hours) and manual synchronization of the fork with the upstream repository using the Fork-Sync-With-Upstream-action. Includes error handling for workflow suspension.
2. chore(seal):
- 	Update the SEALData.__call__ method in hugegraph_ml/models/seal.py to remove the assignment of subsample_ratio for both "train" and other split types, replacing it with pass statements.
- Update the file path string formatting for saving subsampled data.
These changes help automate repository maintenance and clarify the SEALData subsampling …
> chore: add GitHub Actions for auto upstream sync and update SEALData subsample logic

- hugegraph-llm/README.md
Added explicit instructions for creating a .env configuration file under hugegraph-llm if it does not exist, to help new users avoid setup issues.
> docs: update README with improved setup instructions
