hugegraph-python/src/api/graph.py

[fix] function getEdgeByPage(): the generated query url does not include the parameter page

---

hugegraph-llm/README.md
hugegraph-llm/examples/build_kg_test.py
hugegraph-llm/src/config/config.ini
hugegraph-llm/src/hugegraph_llm/llms/ernie_bot.py
hugegraph-llm/src/hugegraph_llm/operators/common_op/check_schema.py
hugegraph-llm/src/hugegraph_llm/operators/hugegraph_op/commit_to_hugegraph.py
hugegraph-llm/src/hugegraph_llm/operators/hugegraph_op/schema_manager.py
hugegraph-llm/src/hugegraph_llm/operators/kg_construction_task.py
hugegraph-llm/src/hugegraph_llm/operators/llm_op/disambiguate_data.py
hugegraph-llm/src/hugegraph_llm/operators/llm_op/info_extract.py
hugegraph-llm/src/tests/operators/common_op/test_check_schema.py
hugegraph-llm/src/tests/operators/llm_op/test_disambiguate_data.py
hugegraph-llm/src/tests/operators/llm_op/test_info_extract.py

refactor construct knowledge graph task

feat: refactor construct knowledge graph task

---

hugegraph-llm/examples/build_kg_test.py
hugegraph-llm/examples/graph_rag_test.py
hugegraph-llm/requirements.txt
hugegraph-llm/src/config/config.ini
hugegraph-llm/src/hugegraph_llm/llms/ernie_bot.py
hugegraph-llm/src/hugegraph_llm/operators/common_op/nltk_helper.py
hugegraph-llm/src/hugegraph_llm/operators/graph_rag_task.py
hugegraph-llm/src/hugegraph_llm/operators/hugegraph_op/commit_to_hugegraph.py
hugegraph-llm/src/hugegraph_llm/operators/hugegraph_op/graph_rag_query.py
hugegraph-llm/src/hugegraph_llm/operators/kg_construction_task.py
hugegraph-llm/src/hugegraph_llm/operators/llm_op/answer_synthesize.py
hugegraph-llm/src/hugegraph_llm/operators/llm_op/keyword_extract.py
hugegraph-llm/src/hugegraph_llm/utils/config.py
hugegraph-llm/src/hugegraph_llm/utils/gradio_demo.py

```
export PYTHONPATH=${PROJECT_ROOT_DIR}/hugegraph-llm/src:${PROJECT_ROOT_DIR}/hugegraph-python-client/src
python3 ./hugegraph-llm/src/hugegraph_llm/utils/gradio_demo.py
```

feat: Introduce gradio for creating interactive and visual demo

---

scripts/apache-release.sh

chore: add release scripts

---

DISCLAIMER

TODO: Remember delete & create `release-1.3.0 ` branch after this PR merged

chore: create DISCLAIMER file for ASF

---

hugegraph-llm/README.md

fix https://github.com/apache/incubator-hugegraph-ai/issues/38
refer: https://hugegraph.apache.org/cn/docs/quickstart/hugegraph-ai/
Add environment requirements, preparation, and examples about:
1. Build a knowledge graph in HugeGraph through LLM
2. Retrieval augmented generation (RAG) based on HugeGraph
If there are any omissions or  something need to be supplemented, please comment.

doc: update llm readme

---

hugegraph-python-client/src/pyhugegraph/api/version.py
hugegraph-python-client/src/pyhugegraph/client.py
hugegraph-python-client/src/tests/api/test_version.py
hugegraph-python-client/src/tests/client_utils.py

implement version api, add unit test
refer: https://hugegraph.apache.org/cn/docs/clients/restful-api/other/
close https://github.com/apache/incubator-hugegraph-ai/issues/14

feat: add version api & test

---

hugegraph-llm/src/hugegraph_llm/demo/rag_web_demo.py

we can test url for any openai-style api

fix: change openai base url

---

hugegraph-llm/README.md

Certainly, here is the translation of the provided content into English:
1. Environment Requirements: Modify the description for `hg` to hg-server` for further specificity.
2. Preparation: Change the numbering style.

doc: revise environment dependencies; update preparation

---

hugegraph-llm/README.md
hugegraph-llm/src/hugegraph_llm/api/models/rag_requests.py
hugegraph-llm/src/hugegraph_llm/api/rag_api.py
hugegraph-llm/src/hugegraph_llm/demo/rag_web_demo.py
hugegraph-llm/src/hugegraph_llm/models/llms/init_llm.py
hugegraph-llm/src/hugegraph_llm/models/llms/openai.py
hugegraph-llm/src/hugegraph_llm/operators/document_op/word_extract.py
hugegraph-llm/src/hugegraph_llm/operators/graph_rag_task.py
hugegraph-llm/src/hugegraph_llm/operators/hugegraph_op/graph_rag_query.py
hugegraph-llm/src/hugegraph_llm/operators/hugegraph_op/schema_manager.py
hugegraph-llm/src/hugegraph_llm/operators/index_op/semantic_id_query.py
hugegraph-llm/src/hugegraph_llm/operators/llm_op/answer_synthesize.py
hugegraph-llm/src/hugegraph_llm/operators/llm_op/disambiguate_data.py
hugegraph-llm/src/hugegraph_llm/operators/llm_op/keyword_extract.py
hugegraph-llm/src/hugegraph_llm/utils/decorators.py
hugegraph-llm/src/hugegraph_llm/utils/graph_index_utils.py

feat(llm): support graph_rag_recall api

---

hugegraph-python-client/src/pyhugegraph/api/schema_manage/property_key.py

As title, also mark TODO for update_strategy

feat(client): support complete data type for PropertyKey

---

.asf.yaml

Update README & Relative doc later

chore: update graph ai repo desc

---

.gitattributes

chore(dist): add `.gitattributes` for exporting source package

---

hugegraph-llm/src/hugegraph_llm/config/llm_config.py
hugegraph-llm/src/hugegraph_llm/models/embeddings/openai.py
hugegraph-llm/src/hugegraph_llm/models/llms/openai.py

Change default config name to match the variable name.

fix(llm): use empty str for llm config

---

hugegraph-llm/src/hugegraph_llm/config/prompt_config.py
hugegraph-llm/src/hugegraph_llm/demo/rag_demo/rag_block.py
hugegraph-llm/src/hugegraph_llm/operators/index_op/gremlin_example_index_query.py
hugegraph-llm/src/hugegraph_llm/resources/demo/css.py

1. Improve the prompt by adding **Please write your answer using Markdown with MathJax syntax, where inline math is wrapped with `$...$`**
2. Change gr.Textbox to gr.Markdown
3. Add CSS

refactor(llm): support mathjax in rag query block V1

---

hugegraph-llm/src/hugegraph_llm/operators/llm_op/property_graph_extract.py
hugegraph-python-client/src/pyhugegraph/api/traverser.py

feat(llm): add post method for paths-api

---

hugegraph-llm/src/hugegraph_llm/demo/rag_demo/app.py
hugegraph-llm/src/hugegraph_llm/utils/hugegraph_utils.py
hugegraph-llm/src/hugegraph_llm/utils/log.py
hugegraph-python-client/setup.py
hugegraph-python-client/src/pyhugegraph/utils/log.py

Modifications:-
- now all logs (gradio + rag) are visible in llm-server.log
- reduced some flooding gradio logs

fix(llm): Merge all logs into one file

---

.github/workflows/hugegraph-python-client.yml
.github/workflows/pylint.yml

refactor: use uv for the CI action

---

hugegraph-llm/src/hugegraph_llm/api/models/rag_requests.py
hugegraph-llm/src/hugegraph_llm/api/rag_api.py
hugegraph-llm/src/hugegraph_llm/demo/rag_demo/text2gremlin_block.py
hugegraph-llm/src/hugegraph_llm/operators/hugegraph_op/graph_rag_query.py

refactor(llm): replace vid by full vertexes info

---

.asf.yaml
.github/workflows/hugegraph-python-client.yml
hugegraph-llm/README.md
hugegraph-llm/src/hugegraph_llm/operators/llm_op/property_graph_extract.py

See #210 
Main change of regex: matching `(\[.*])` -> matching `({.*})`.
tested models:
- qwen-max
- qwen-plus
- deepseek-v3

fix(llm): Align regex extraction of json to json format of prompt

---

hugegraph-python-client/README.md

fix #218 
Id of vertex in sample code in README is hardcoding, but which should be get by `id` feild.

fix(clien): fix documentation sample code error

---

hugegraph-llm/src/hugegraph_llm/demo/rag_demo/vector_graph_block.py

feat(llm): Textbox to Code #217

---

hugegraph-llm/src/hugegraph_llm/models/embeddings/base.py
hugegraph-llm/src/hugegraph_llm/models/embeddings/ollama.py
hugegraph-llm/src/hugegraph_llm/operators/index_op/build_semantic_index.py
hugegraph-llm/src/hugegraph_llm/operators/index_op/build_vector_index.py
hugegraph-llm/src/tests/indices/test_vector_index.py

when using ollama embedding models, `update_vid_embedding` bug
**gradio.exceptions.Error: "'Client' object has no attribute 'embed'"**

fix(llm): ollama batch embedding bug

---

hugegraph-llm/src/hugegraph_llm/utils/embedding_utils.py

Reworked get_embeddings_parallel to use asyncio.gather for batch processing, ensuring output order matches input. Added a helper for batch progress updates and improved progress bar accuracy.

fix(llm): refactor embedding parallelization to preserve order
